### PR TITLE
fix: bindFirestoreRef not reacting to getter

### LINKED ISSUE #1495: returned values from `useDocument` and `useCollection` using a getter aren't reactive
### Reproduction

https://stackblitz.com/edit/vitejs-vite-wlriny?file=src%2FApp.vue

### Steps to reproduce the bug

The reproduction example show ways to use `useDocument` and `useCollection`

```ts
const userDocumentComputed = useDocument(
  computed(() => {
    return currentUser.value ? doc(db, 'users', currentUser.value.uid) : null;
  })
);

const userDocument = useDocument(() => {
  return currentUser.value ? doc(db, 'users', currentUser.value.uid) : null;
});

const userFriends = useCollection(() => {
  return currentUser.value
    ? collection(db, 'users', currentUser.value.uid, 'friends')
    : null;
});

const userFriendsComputed = useCollection(
  computed(() => {
    return currentUser.value
      ? collection(db, 'users', currentUser.value.uid, 'friends')
      : null;
  })
);
```

- Login as a user
- Noticed how the data coming from a function won't change to the correct values, but data coming from computed will
- Logout and login as another user

### Expected behavior

Acording to the documentation, you can pass both a getter or a computed().
https://vuefire.vuejs.org/guide/realtime-data.html#Declarative-realtime-data.
So `userDocument` and `userFriends` should update when you change user

### Actual behavior

refs that were created by using an getter are not reactive (`userDocument` and `userFriends` )

### Additional information

This looks like a bug as the documentation show the usage of a _getter_.

Either way, I'm willing to dive into the source code to understand/fix the bug, or to update the documentation to make it clear that getters aren't supported.

### PR DESCRIPTION
**Pull request by ralacerda**
Closes #1495

Checking if the `docOrCollectionRef` is a ref before setting up a watch to re-bind the firestore meant getters weren't being watched. 

Using `watch(() => toValue(docOrCollectionRef), bindFirestoreRef)` will keep the old behaviour of tracking refs and computeds while also tracking getters.

In this case, we also don't need to check what `docOrCollectionRef` is.
Unless there is a cost in watching an non-reactive source (I don't think so, but I'm not sure).

I'm still learning my way around the tests, I tried the following, but the tests hangs and fails:

```ts
it('can be bound to a getter', async () => {
  const listCollectionRef = collection<{ name: string }>()
  const listRef = ref<null | CollectionReference>(null)

  const { wrapper } = factory({
    ref: () => listRef.value,
  })

  await addDoc(listCollectionRef, { name: 'a' })
  await addDoc(listCollectionRef, { name: 'b' })

  expect(wrapper.vm.list).toHaveLength(0)
  listRef.value = listCollectionRef
  expect(wrapper.vm.list).toContainEqual({ name: 'a' })
  expect(wrapper.vm.list).toContainEqual({ name: 'b' })
})
```

But I must be doing something wrong because even when I use `ref: listRef` it also fails, but `ref: listCollectionRef` it works.
I'll keep the PR as a draft while I work on those tests.

### CODE REVIEW

File: src/firestore/useFirestoreRef.ts [hunk 1]
```diff
@@ -164,9 +164,7 @@ export function _useFirestoreRef(
   }
 
   let stopWatcher = noop
-  if (isRef(docOrCollectionRef)) {
```
Comment (posva) [inline src/firestore/useFirestoreRef.ts:167]: Let's keep isRef or typeof is function

File: src/firestore/useFirestoreRef.ts [hunk 2]
```diff
@@ -164,9 +164,7 @@ export function _useFirestoreRef(
...
-    stopWatcher = watch(docOrCollectionRef, bindFirestoreRef)
-  }
+  stopWatcher = watch(() => toValue(docOrCollectionRef), bindFirestoreRef)
```
Comment (posva) [inline src/firestore/useFirestoreRef.ts:167]: Since the getter function returns the actual value, toValue shouldn't be needed

**Review by posva — CHANGES_REQUESTED** [review]
For the test: rather than using a ref of a collection, put a string in the ref and use `() => collection(db, '...', myRef.value)`

File: src/firestore/useFirestoreRef.ts (hunk 1 above)
Comment (posva) [reply src/firestore/useFirestoreRef.ts:167]: BTW, it is for performance reasons

**Comment by posva** [comment]
Could you also add the same for `useDatabaseRef.ts` and `storage.ts`?

**Comment by ralacerda** [comment]
I returned the `isRef` checking but also included `typeof === 'function'` as you suggested.

I wrote a test for `useDatabase` that it's pretty similar to the one above.

I was able to add a test for `useDocument` with your suggestion.

The current test uses an named collection (`populatedCollection` and `emptyCollection`) which I guess can be a problem if another test tries to use the same named collection. 

Should I use `collection()` util to create an unique collection for this test, and then, inside it create and document and `populatedCollection`?

Something like
```diff

it('can be bound to a getter', async () => {
-  const listCollectionRef = collection<{ name: string }>(
-    'populatedCollection'
-  )
+  const parentCollectionName = collection().path.split('/').at(-1)
+  const populatedCollection = collection<{ name: string }>(
+    parentCollectionName,
+    'parentDocument',
+    'populatedCollection'
+  )
  const collectionName = ref('populatedCollection')

  const { wrapper, promise } = factory({
-    ref: () => collection(collectionName.value),
+    ref: () =>
+      collection(
+        parentCollectionName,
+        'parentDocument',
+        collectionName.value
+      ),
  })

  await promise.value
-  await addDoc(listCollectionRef, { name: 'a' })
-  await addDoc(listCollectionRef, { name: 'b' })
+  await addDoc(populatedCollection, { name: 'a' })
+  await addDoc(populatedCollection, { name: 'b' })

  expect(wrapper.vm.list).toHaveLength(2)
  expect(wrapper.vm.list).toContainEqual({ name: 'a' })
  expect(wrapper.vm.list).toContainEqual({ name: 'b' })

  collectionName.value = 'emptyCollection'
  await nextTick()
  await promise.value
  await nextTick()
  expect(wrapper.vm.list).toHaveLength(0)
})

```

I wanted to ask because I'm not sure if it's really needed.

**Comment by posva** [comment]
It should be fine the way you did it it, no need to create a subcollection 🙂

**Review by posva — APPROVED** [review]
Thanks a lot!

**Comment by posva** [comment]
I published a patch 👍
